import { useEffect, useState } from 'react';
import { ArrowLeft, FileText, Save, ExternalLink, Plus, Trash2, ChevronUp, ChevronDown, GripVertical, Eye, ListChecks, LayoutTemplate } from 'lucide-react';
import { useAuth } from '@/lib/auth';
import { fetchEditablePage, saveEditablePage, PAGE_DEFAULTS } from '@/lib/adminConfig';
import { fetchProfileQuestions, saveProfileQuestion, deleteProfileQuestion, reorderProfileQuestions, PROFILE_SECTIONS, type ProfileQuestion, type ProfileQuestionType } from '@/lib/profileQuestions';

const PAGE_KEYS = ['about', 'privacy', 'terms'] as const;
const QUESTION_TYPES: { value: ProfileQuestionType; label: string }[] = [
  { value: 'short_text', label: 'Short answer' }, { value: 'long_text', label: 'Paragraph' }, { value: 'number', label: 'Number' }, { value: 'year', label: 'Year' }, { value: 'url', label: 'Link / URL' }, { value: 'select', label: 'Dropdown' },
];

export function AdminPagesModerationPage({ navigate }: { navigate: (path: string) => void }) {
  const { user, isAdmin, loading } = useAuth();
  const [active, setActive] = useState<typeof PAGE_KEYS[number]>('about'); const [title,setTitle]=useState(''); const [content,setContent]=useState(''); const [saving,setSaving]=useState(false); const [msg,setMsg]=useState('');
  const [questions,setQuestions]=useState<ProfileQuestion[]>([]); const [editing,setEditing]=useState<ProfileQuestion|null>(null); const [question,setQuestion]=useState(''); const [section,setSection]=useState<string>('Personal Details'); const [type,setType]=useState<ProfileQuestionType>('short_text'); const [options,setOptions]=useState(''); const [required,setRequired]=useState(false); const [publicDefault,setPublicDefault]=useState(true); const [showInCard,setShowInCard]=useState(true);
  const loadPage=async(slug:typeof PAGE_KEYS[number])=>{const page=await fetchEditablePage(slug);setTitle(page.title);setContent(page.content);};
  const loadQuestions=async()=>{try{setQuestions(await fetchProfileQuestions(true));}catch(e){setMsg(e instanceof Error?e.message:'Could not load profile questions.');}};
  useEffect(()=>{if(isAdmin)void loadPage(active);},[isAdmin,active]); useEffect(()=>{if(isAdmin)void loadQuestions();},[isAdmin]);
  if(loading)return <div className="pt-32 container-prose text-center">Loading…</div>; if(!user||!isAdmin)return <div className="pt-32 container-prose text-center">Admin access required.</div>;
  const save=async()=>{try{setSaving(true);await saveEditablePage(active,title,content);setMsg('Page saved.');}catch(e){setMsg(e instanceof Error?e.message:'Could not save page.');}finally{setSaving(false);}};
  const resetQuestion=()=>{setEditing(null);setQuestion('');setSection('Personal Details');setType('short_text');setOptions('');setRequired(false);setPublicDefault(true);setShowInCard(true);};
  const editQuestion=(q:ProfileQuestion)=>{setEditing(q);setQuestion(q.question);setSection(q.section);setType(q.type);setOptions(q.options.join('\n'));setRequired(q.required);setPublicDefault(q.public_default);setShowInCard(q.show_in_profile_card!==false);window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'});};
  const saveQuestion=async()=>{if(!question.trim()){setMsg('Enter a question first.');return;}try{const saved=await saveProfileQuestion({id:editing?.id,question,section,type,options:options.split('\n').map(x=>x.trim()).filter(Boolean),required,public_default:publicDefault,show_in_profile_card:showInCard,sort_order:editing?.sort_order??questions.length});setQuestions(v=>editing?v.map(x=>x.id===saved.id?saved:x):[...v,saved]);setMsg('Profile question saved.');resetQuestion();}catch(e){setMsg(e instanceof Error?e.message:'Could not save question.');}};
  const removeQuestion=async(id:string)=>{if(!confirm('Remove this profile question?'))return;try{await deleteProfileQuestion(id);setQuestions(v=>v.filter(x=>x.id!==id));setMsg('Question removed.');}catch(e){setMsg(e instanceof Error?e.message:'Could not remove question.');}};
  const move=async(index:number,direction:-1|1)=>{const target=index+direction;if(target<0||target>=questions.length)return;const next=[...questions];[next[index],next[target]]=[next[target],next[index]];setQuestions(next);try{await reorderProfileQuestions(next.map(q=>q.id));}catch(e){setMsg(e instanceof Error?e.message:'Could not reorder questions.');}};
  return <div className="pt-24 pb-20 container-prose animate-fade-in"><div className="max-w-7xl mx-auto"><button onClick={()=>navigate('/admin')} className="inline-flex items-center gap-1.5 text-sm mb-7" style={{color:'var(--color-text-muted)'}}><ArrowLeft className="w-4 h-4"/> Admin Dashboard</button><header className="mb-8"><div className="inline-flex items-center gap-2 text-xs uppercase tracking-[.18em] font-semibold" style={{color:'var(--color-teal-dark)'}}><FileText className="w-4 h-4"/> Admin content</div><h1 className="font-serif text-4xl font-semibold mt-2">WebApp Pages Moderation</h1><p className="text-sm mt-2" style={{color:'var(--color-text-muted)'}}>Edit heavy-text pages and manage the profile questions that appear on reader profile cards.</p></header>
    <div className="grid grid-cols-1 lg:grid-cols-[220px_1fr] gap-6"><aside className="surface-card p-3 h-fit space-y-2">{PAGE_KEYS.map(key=><button key={key} onClick={()=>{setActive(key);setMsg('');}} className="w-full text-left rounded-xl p-3" style={{background:active===key?'rgba(0,151,178,.09)':'transparent',color:'var(--color-text)'}}><strong className="block">{PAGE_DEFAULTS[key].title}</strong><span className="text-xs" style={{color:'var(--color-text-muted)'}}>/{key}</span></button>)}<div className="pt-2 border-t" style={{borderColor:'var(--color-border)'}}><button className="w-full btn-ghost text-xs" onClick={()=>navigate(`/${active}`)}><ExternalLink className="w-3.5 h-3.5"/> Preview page</button></div></aside>
      <section className="surface-card p-6"><div className="flex items-center justify-between gap-3 mb-5"><div><p className="text-xs uppercase tracking-widest font-semibold" style={{color:'var(--color-teal-dark)'}}>Editing</p><h2 className="font-serif text-2xl font-semibold">{title}</h2></div><button className="btn-primary !w-auto" disabled={saving} onClick={save}><Save className="w-4 h-4"/>{saving?'Saving…':'Save Page'}</button></div><div className="space-y-4"><div><label className="label">Page title</label><input value={title} onChange={e=>setTitle(e.target.value)} className="input-field"/></div><div><label className="label">Page copy</label><textarea value={content} onChange={e=>setContent(e.target.value)} className="input-field min-h-[520px] resize-y font-mono text-sm leading-6"/></div></div></section></div>

    <section className="surface-card p-6 mt-8"><div className="flex items-center gap-3 mb-5"><div className="w-10 h-10 rounded-2xl grid place-items-center gradient-teal"><LayoutTemplate className="w-5 h-5 text-white"/></div><div><p className="text-xs uppercase tracking-[.18em] font-semibold" style={{color:'var(--color-teal-dark)'}}>Profile page moderation</p><h2 className="font-serif text-2xl font-semibold mt-1">Profile Card controls</h2></div></div><p className="text-sm leading-6 max-w-3xl" style={{color:'var(--color-text-muted)'}}>Use each reader's privacy controls for personal fields, and use the question editor below to decide whether an answer is eligible to appear on the downloadable/public profile card.</p><div className="mt-5 rounded-2xl p-4 flex flex-wrap items-center justify-between gap-3" style={{background:'linear-gradient(135deg,rgba(0,151,178,.09),rgba(53,211,217,.12))',border:'1px solid var(--color-border)'}}><div><p className="font-semibold">Questions shown on profile cards</p><p className="text-xs mt-1" style={{color:'var(--color-text-muted)'}}>Toggle this per question in the editor. Existing user privacy settings still win.</p></div><span className="text-sm font-semibold" style={{color:'var(--color-teal-dark)'}}>{questions.filter(q=>q.show_in_profile_card!==false).length} enabled</span></div></section>

    <section className="surface-card p-6 mt-8"><div className="flex flex-wrap items-center justify-between gap-4 mb-6"><div><div className="flex items-center gap-2"><ListChecks className="w-5 h-5" style={{color:'var(--color-cyan-dark)'}}/><p className="text-xs uppercase tracking-[.18em] font-semibold" style={{color:'var(--color-teal-dark)'}}>Profile form builder</p></div><h2 className="font-serif text-3xl font-semibold mt-1">Profile Questions</h2><p className="text-sm mt-2" style={{color:'var(--color-text-muted)'}}>Like a lightweight Google Forms editor: choose the section, question type, visibility default, and reorder the questions.</p></div><button type="button" className="btn-primary !w-auto" onClick={resetQuestion}><Plus className="w-4 h-4"/> Add question</button></div>
      <div className="grid grid-cols-1 xl:grid-cols-[1fr_360px] gap-6"><div className="space-y-3">{questions.length===0?<div className="py-10 text-center" style={{color:'var(--color-text-muted)'}}>No profile questions yet.</div>:questions.map((q,i)=><div key={q.id} className="rounded-2xl p-4" style={{background:'var(--color-paper)',border:'1px solid var(--color-border)'}}><div className="flex gap-3"><GripVertical className="w-4 h-4 mt-1" style={{color:'var(--color-text-muted)'}}/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="text-[10px] uppercase tracking-wider font-bold px-2 py-1 rounded-full" style={{background:'rgba(8,145,178,.09)',color:'var(--color-teal-dark)'}}>{q.section}</span><span className="text-[10px] uppercase tracking-wider" style={{color:'var(--color-text-muted)'}}>{QUESTION_TYPES.find(x=>x.value===q.type)?.label}</span>{q.required&&<span className="text-[10px] font-bold">Required</span>}{q.show_in_profile_card!==false&&<span className="text-[10px] font-bold" style={{color:'var(--color-teal-dark)'}}>Profile card</span>}</div><p className="font-semibold mt-2">{q.question}</p>{q.options.length>0&&<p className="text-xs mt-1" style={{color:'var(--color-text-muted)'}}>Options: {q.options.join(' · ')}</p>}<p className="text-xs mt-2" style={{color:q.public_default?'var(--color-teal-dark)':'var(--color-text-muted)'}}><Eye className="inline w-3.5 h-3.5 mr-1"/>{q.public_default?'Public by default':'Private by default'}</p></div><div className="flex items-center gap-1"><button type="button" onClick={()=>move(i,-1)} disabled={i===0} className="p-2 rounded-lg" title="Move up"><ChevronUp className="w-4 h-4"/></button><button type="button" onClick={()=>move(i,1)} disabled={i===questions.length-1} className="p-2 rounded-lg" title="Move down"><ChevronDown className="w-4 h-4"/></button><button type="button" onClick={()=>editQuestion(q)} className="btn-ghost !w-auto !px-3 text-xs">Edit</button><button type="button" onClick={()=>removeQuestion(q.id)} className="p-2 rounded-lg" title="Delete"><Trash2 className="w-4 h-4"/></button></div></div></div>)}</div>
      <div className="rounded-2xl p-5 h-fit" style={{background:'linear-gradient(160deg,rgba(8,145,178,.08),rgba(94,234,212,.08))',border:'1px solid var(--color-border)'}}><div className="flex items-center justify-between mb-4"><div><p className="text-xs uppercase tracking-wider font-semibold" style={{color:'var(--color-teal-dark)'}}>{editing?'Edit question':'New question'}</p><h3 className="font-serif text-xl font-semibold">Question editor</h3></div>{editing&&<button type="button" className="text-xs underline" onClick={resetQuestion}>Cancel</button>}</div><div className="space-y-3"><div><label className="label">Section</label><select value={section} onChange={e=>setSection(e.target.value)} className="input-field">{PROFILE_SECTIONS.map(s=><option key={s}>{s}</option>)}</select></div><div><label className="label">Question</label><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder="What book changed your life?" className="input-field"/></div><div><label className="label">Question type</label><select value={type} onChange={e=>setType(e.target.value as ProfileQuestionType)} className="input-field">{QUESTION_TYPES.map(t=><option key={t.value} value={t.value}>{t.label}</option>)}</select></div>{type==='select'&&<div><label className="label">Dropdown options</label><textarea value={options} onChange={e=>setOptions(e.target.value)} placeholder={'Fiction\nNon-fiction\nPoetry'} className="input-field min-h-24"/><p className="text-[11px] mt-1" style={{color:'var(--color-text-muted)'}}>One option per line.</p></div>}<label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={required} onChange={e=>setRequired(e.target.checked)}/> Required</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={publicDefault} onChange={e=>setPublicDefault(e.target.checked)}/> Visible by default</label><label className="flex items-center gap-2 text-sm rounded-xl p-3" style={{background:'rgba(0,151,178,.08)'}}><input type="checkbox" checked={showInCard} onChange={e=>setShowInCard(e.target.checked)}/> Show answer on profile card</label><button type="button" className="btn-primary w-full" onClick={saveQuestion}><Save className="w-4 h-4"/>{editing?'Update question':'Add question'}</button></div></div></div>
    </section>{msg&&<p className="mt-4 text-sm" style={{color:'var(--color-teal-dark)'}}>{msg}</p>}
  </div></div>;
}
