import { useEffect, useRef, useState, type ReactNode, type ChangeEvent, type FormEvent } from 'react';
import { ArrowLeft, Camera, CheckCircle, Eye, EyeOff, Globe, Instagram, Link2, Mail, Save, Upload, User, BookOpen, Library, Minus, Plus, Users, X, Lock, Unlock, ImagePlus, Clock3, Download, Sparkles, ExternalLink } from 'lucide-react';
import { useAuth } from '@/lib/auth';
import { fetchMyAcceptedReviews, fetchMyPublishedReviews, updateProfile, uploadAvatarImage, uploadProfileHeaderImage, type AcceptedReviewCard } from '@/lib/reviews';
import { RwStarRating } from '@/components/RwStarRating';
import { createStory, uploadStoryImage, fetchFollowStats, fetchConnections, fetchActiveStories, type FollowStats, type ConnectionProfile, type Story } from '@/lib/social';
import { fetchProfileQuestions, type ProfileQuestion } from '@/lib/profileQuestions';
import { ProfileCard, type ProfileCardData } from '@/components/ProfileCard';

interface ProfilePageProps { navigate: (path: string) => void; }
type SocialLink = { platform: string; url: string };
const SOCIAL_PLATFORMS = ['instagram','goodreads','wattpad','facebook','linkedin','x'] as const;
const SOCIAL_LABELS: Record<string,string> = { instagram:'Instagram', goodreads:'Goodreads', wattpad:'Wattpad', facebook:'Facebook', linkedin:'LinkedIn', x:'X' };
const DEFAULT_VIS: Record<string, boolean> = { avatar:true,name:true,email:false,header_image:true,books_read_this_month:true,total_books_read:true,reading_since:true,favorite_book:true,favorite_author:true,favorite_genre:true };

export function ProfilePage({ navigate }: ProfilePageProps) {
  const { user, profile, loading, refreshProfile } = useAuth();
  const [name,setName]=useState(''); const [favoriteBook,setFavoriteBook]=useState(''); const [booksReadThisMonth,setBooksReadThisMonth]=useState(''); const [totalBooksRead,setTotalBooksRead]=useState(''); const [readingSince,setReadingSince]=useState(''); const [favoriteAuthor,setFavoriteAuthor]=useState(''); const [favoriteGenre,setFavoriteGenre]=useState('');
  const [avatarUrl,setAvatarUrl]=useState(''); const [headerUrl,setHeaderUrl]=useState(''); const [avatarUploading,setAvatarUploading]=useState(false); const [headerUploading,setHeaderUploading]=useState(false);
  const [socialLinks,setSocialLinks]=useState<SocialLink[]>([]); const [answers,setAnswers]=useState<Record<string,unknown>>({}); const [questions,setQuestions]=useState<ProfileQuestion[]>([]);
  const [visibility,setVisibility]=useState<Record<string,boolean>>(DEFAULT_VIS); const [hideFollowers,setHideFollowers]=useState(false); const [hideFollowing,setHideFollowing]=useState(false);
  const [storyUploading,setStoryUploading]=useState(false); const [storyCaption,setStoryCaption]=useState(''); const [myStory,setMyStory]=useState<Story|null>(null);
  const [saving,setSaving]=useState(false); const [saved,setSaved]=useState(false); const [error,setError]=useState<string|null>(null); const [accepted,setAccepted]=useState<AcceptedReviewCard[]>([]); const [published,setPublished]=useState<AcceptedReviewCard[]>([]);
  const [followStats,setFollowStats]=useState<FollowStats>({followers:0,following:0,is_following:false}); const [connectionKind,setConnectionKind]=useState<'followers'|'following'|null>(null); const [connections,setConnections]=useState<ConnectionProfile[]>([]);
  const avatarInputRef=useRef<HTMLInputElement>(null); const headerInputRef=useRef<HTMLInputElement>(null); const storyInputRef=useRef<HTMLInputElement>(null);

  useEffect(()=>{ if(!profile) return; setName(profile.name||''); setFavoriteBook(profile.favorite_book||''); setBooksReadThisMonth(profile.books_read_this_month==null?'':String(profile.books_read_this_month)); setTotalBooksRead(profile.total_books_read==null?'':String(profile.total_books_read)); setReadingSince(profile.reading_since==null?'':String(profile.reading_since)); setFavoriteAuthor(profile.favorite_author||''); setFavoriteGenre(profile.favorite_genre||''); setAvatarUrl(profile.avatar_url||''); setHeaderUrl(profile.header_image_url||''); setSocialLinks((profile.social_links||[]).slice(0,3)); setAnswers(profile.profile_answers||{}); setHideFollowers(!!profile.hide_followers); setHideFollowing(!!profile.hide_following); setVisibility({...DEFAULT_VIS,...(profile.profile_visibility||{})}); },[profile]);
  useEffect(()=>{ if(!user) return; let alive=true; Promise.allSettled([fetchMyAcceptedReviews(),fetchMyPublishedReviews(),fetchProfileQuestions(),fetchActiveStories(user.id)]).then((results)=>{ if(!alive) return; const [a,p,q,s]=results; if(a.status==='fulfilled') setAccepted(a.value); if(p.status==='fulfilled') setPublished(p.value); if(q.status==='fulfilled') setQuestions(q.value); if(s.status==='fulfilled') setMyStory(s.value.find(x=>x.user_id===user.id)||null); const names=['Accepted reviews','Published reviews','Profile questions','Stories']; const failures=[a,p,q,s].map((x,i)=>x.status==='rejected'?`${names[i]}: ${(x.reason as {message?:string})?.message||'request failed'}`:null).filter(Boolean); if(failures.length) setError(`Some profile data could not be loaded — ${failures.join(' · ')}`); }).catch(()=>undefined); if(profile?.novelty_username) fetchFollowStats(profile.novelty_username).then(setFollowStats).catch(()=>undefined); return ()=>{alive=false;}; },[user?.id,profile?.novelty_username]);

  const ratedPublished=published.filter(r=>Number(r.reviewers_rating)>0);
  const avgRating=ratedPublished.length?ratedPublished.reduce((sum,r)=>sum+Number(r.reviewers_rating),0)/ratedPublished.length:null;
  const publishedNos=new Set(published.map(r=>String(r.review_no||'')));
  const cardData: ProfileCardData={name:visibility.name?name:null,username:profile?.novelty_username||null,avatarUrl:visibility.avatar?avatarUrl:null,headerImageUrl:visibility.header_image?headerUrl:null,socialLinks:socialLinks.slice(0,3),booksThisMonth:visibility.books_read_this_month?(Number(booksReadThisMonth)||0):null,totalBooksRead:visibility.total_books_read?(Number(totalBooksRead)||0):null,publishedBooks:published.length,avgRating:avgRating&&Number.isFinite(avgRating)?avgRating:null,readingSince:visibility.reading_since?(Number(readingSince)||null):null,favoriteBook:visibility.favorite_book?favoriteBook:null,favoriteAuthor:visibility.favorite_author?favoriteAuthor:null,favoriteGenre:visibility.favorite_genre?favoriteGenre:null,publishedReviews:published.map(r=>({id:String(r.id),reviewNo:r.review_no||null,title:r.book_title||'Untitled review',author:r.author||'',coverUrl:r.book_cover||null,rating:Number(r.reviewers_rating)||null})),answers:Object.fromEntries(questions.filter(q=>visibility[`question:${q.key}`]!==false).map(q=>[q.key,answers[q.key]])),questions};

  const uploadAvatar=async(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f||!user)return;setAvatarUploading(true);setError(null);try{const {publicUrl}=await uploadAvatarImage(f,user.id);setAvatarUrl(publicUrl);await updateProfile(user.id,{avatar_url:publicUrl});await refreshProfile();}catch(err){setError(err instanceof Error?err.message:'Profile picture upload failed.');}finally{setAvatarUploading(false);}};
  const uploadHeader=async(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f||!user)return;setHeaderUploading(true);setError(null);try{const {publicUrl}=await uploadProfileHeaderImage(f,user.id);setHeaderUrl(publicUrl);await updateProfile(user.id,{header_image_url:publicUrl});await refreshProfile();}catch(err){setError(err instanceof Error?err.message:'Header image upload failed.');}finally{setHeaderUploading(false);}};
  const save=async(e:FormEvent)=>{e.preventDefault();if(!user)return;const year=readingSince.trim()?Number(readingSince):null;if(year!==null&&(!/^\d{4}$/.test(readingSince)||year<1900||year>new Date().getFullYear())){setError('Reading Since must be a valid year.');return;}if([booksReadThisMonth,totalBooksRead].some(v=>v.trim()&&!/^\d+$/.test(v))){setError('Book counts must contain whole numbers only.');return;}const cleanLinks=socialLinks.filter(x=>x.url.trim()).slice(0,3).map(x=>({platform:x.platform,url:/^https?:\/\//i.test(x.url.trim())?x.url.trim():`https://${x.url.trim()}`}));setSaving(true);setError(null);try{await updateProfile(user.id,{name:name.trim()||null,avatar_url:avatarUrl||null,header_image_url:headerUrl||null,social_links:cleanLinks,instagram_id:cleanLinks.find(x=>x.platform==='instagram')?.url.replace(/^https?:\/\//,'').replace(/^www\./,'')||null,website:null,favorite_book:favoriteBook.trim()||null,books_read_this_month:booksReadThisMonth.trim()?Number(booksReadThisMonth):null,total_books_read:Math.max(Number(totalBooksRead)||0,accepted.length),reading_since:year,favorite_author:favoriteAuthor.trim()||null,favorite_genre:favoriteGenre.trim()||null,hide_followers:hideFollowers,hide_following:hideFollowing,profile_visibility:visibility,profile_answers:answers});await refreshProfile();setSaved(true);setTimeout(()=>setSaved(false),2500);}catch(err){setError(err instanceof Error?err.message:'Failed to save profile.');}finally{setSaving(false);}};
  const publishStory=async(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];e.target.value='';if(!f||!user)return;setStoryUploading(true);setError(null);try{const path=await uploadStoryImage(f,user.id);await createStory(path,storyCaption);setStoryCaption('');const s=await fetchActiveStories(user.id);setMyStory(s.find(x=>x.user_id===user.id)||null);}catch(err){setError(err instanceof Error?err.message:'Failed to publish story.');}finally{setStoryUploading(false);}};
  const setSocial=(i:number,key:keyof SocialLink,val:string)=>setSocialLinks(v=>v.map((x,n)=>n===i?{...x,[key]:val}:x));
  const toggleVisibility=(key:string)=>setVisibility(v=>({...v,[key]:!(v[key]??true)}));

  if(loading)return <div className="pt-32 container-prose text-center">Loading profile…</div>;
  if(!user)return <div className="pt-32 container-prose text-center max-w-md mx-auto"><User className="w-12 h-12 mx-auto mb-4"/><h1 className="font-serif text-2xl font-semibold mb-2">Sign In Required</h1><p className="text-sm mb-6" style={{color:'var(--color-text-muted)'}}>Sign in to create your Novelty Library profile.</p><button onClick={()=>navigate('/auth')} className="btn-primary">Sign In</button></div>;

  return <div className="pt-24 pb-20 container-prose animate-fade-in nl-profile-page"><button onClick={()=>navigate('/')} className="inline-flex items-center gap-1.5 text-sm mb-7" style={{color:'var(--color-text-muted)'}}><ArrowLeft className="w-4 h-4"/> Home</button><div className="max-w-6xl mx-auto space-y-7">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[.18em] font-semibold" style={{color:'var(--color-teal-dark)'}}>Your Novelty Library identity</p><h1 className="font-serif text-4xl font-semibold mt-1">Profile Card</h1><p className="text-sm mt-2" style={{color:'var(--color-text-muted)'}}>Build the reader card you want to share — including your reading journey and the reviews you have published with Novelty Library.</p></div><div className="flex gap-2"><button type="button" onClick={()=>navigate(`/profile/@${encodeURIComponent(profile?.novelty_username||'')}`)} className="btn-ghost !w-auto"><ExternalLink className="w-4 h-4"/> View public profile</button></div></div>
    <section className="grid grid-cols-1 lg:grid-cols-[minmax(0,1fr)_280px] gap-6 items-start"><div><ProfileCard data={cardData} download /></div><aside className="surface-card p-5 lg:sticky lg:top-24"><div className="flex items-center gap-2 mb-3"><Sparkles className="w-4 h-4" style={{color:'var(--color-cyan-dark)'}}/><p className="text-xs uppercase tracking-[.18em] font-semibold" style={{color:'var(--color-teal-dark)'}}>Profile assets</p></div><div className="relative w-full aspect-[3/1] rounded-2xl overflow-hidden mb-4" style={{background:'linear-gradient(135deg,#075985,#5eead4)'}}>{headerUrl?<img src={headerUrl} alt="Header" className="w-full h-full object-cover"/>:<div className="h-full grid place-items-center text-white text-xs">Header image · 1500 × 500</div>}<input ref={headerInputRef} type="file" accept="image/jpeg,image/png,image/webp" onChange={uploadHeader} className="hidden"/><button type="button" onClick={()=>headerInputRef.current?.click()} disabled={headerUploading} className="absolute bottom-2 right-2 rounded-full p-2.5 shadow-lg" style={{background:'white',color:'var(--color-teal-dark)'}}>{headerUploading?<Upload className="w-4 h-4 animate-pulse"/>:<Camera className="w-4 h-4"/>}</button></div><p className="text-xs" style={{color:'var(--color-text-muted)'}}>Header image uses a 3:1 composition. The exporter crops it cleanly into every profile-card format.</p><div className="mt-5 pt-5 border-t" style={{borderColor:'var(--color-border)'}}><p className="text-xs font-semibold mb-2">Profile picture</p><input ref={avatarInputRef} type="file" accept="image/jpeg,image/png,image/webp" onChange={uploadAvatar} className="hidden"/><button type="button" onClick={()=>avatarInputRef.current?.click()} className="btn-ghost w-full">{avatarUploading?<Upload className="w-4 h-4 animate-pulse"/>:<Camera className="w-4 h-4"/>} Change photo</button></div></aside></section>

    {myStory && <section className="surface-card p-4 flex flex-wrap items-center gap-4" style={{background:'linear-gradient(90deg,rgba(8,145,178,.08),rgba(94,234,212,.12))'}}><div className="nl-profile-story-ring"><img src={myStory.image_url} alt="Your active story"/></div><div className="min-w-0 flex-1"><p className="text-xs uppercase tracking-[.18em] font-semibold" style={{color:'var(--color-teal-dark)'}}>Story uploaded</p><p className="font-semibold mt-1">Your 24-hour story is live.</p><p className="text-xs mt-1" style={{color:'var(--color-text-muted)'}}>It appears in the home story rail for you and your followers.</p></div><span className="text-xs font-semibold" style={{color:'var(--color-cyan-dark)'}}>LIVE · 24H</span></section>}

    <section className="surface-card p-6 nl-story-composer"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs uppercase tracking-[.18em] font-semibold" style={{color:'var(--color-teal-dark)'}}>24-hour story</p><h2 className="font-serif text-2xl font-semibold mt-1">Share a reading moment</h2><p className="text-sm mt-1" style={{color:'var(--color-text-muted)'}}>Followers will see it above Add Story on Home, Instagram-style.</p></div><button type="button" className="btn-primary !w-auto" onClick={()=>storyInputRef.current?.click()} disabled={storyUploading}><ImagePlus className="w-4 h-4"/>{storyUploading?'Uploading…':'Upload Story'}</button></div><input ref={storyInputRef} type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={publishStory}/><div className="relative mt-4"><Clock3 className="field-icon"/><input value={storyCaption} onChange={e=>setStoryCaption(e.target.value.slice(0,240))} placeholder="Add a short caption (optional)" className="input-field pl-10"/></div></section>

    <form onSubmit={save} className="space-y-7"><section className="surface-card p-6"><div className="mb-5"><p className="text-xs uppercase tracking-[.18em] font-semibold" style={{color:'var(--color-teal-dark)'}}>Personal details</p><h2 className="font-serif text-2xl font-semibold mt-1">Build your reader identity</h2></div><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><PrivacyField label="Name" visible={visibility.name} onToggle={()=>toggleVisibility('name')}><input value={name} onChange={e=>setName(e.target.value)} placeholder="Jane Doe" className="input-field"/></PrivacyField><PrivacyField label="Email" visible={visibility.email} onToggle={()=>toggleVisibility('email')}><div className="relative"><Mail className="field-icon"/><input value={user.email||''} disabled className="input-field pl-10 opacity-50"/></div></PrivacyField></div><div className="mt-6 pt-6" style={{borderTop:'1px solid var(--color-border)'}}><div className="flex flex-wrap items-center justify-between gap-3 mb-4"><div><p className="text-xs uppercase tracking-[.18em] font-semibold" style={{color:'var(--color-teal-dark)'}}>Social links</p><p className="text-sm mt-1" style={{color:'var(--color-text-muted)'}}>Add up to 3 public links that belong to your reader identity.</p></div><Link2 className="w-5 h-5" style={{color:'var(--color-cyan-dark)'}}/></div><div className="space-y-3">{socialLinks.map((link,i)=><div key={`${i}-${link.platform}`} className="grid grid-cols-1 md:grid-cols-[150px_1fr_auto] gap-2 items-center"><select value={link.platform} onChange={e=>setSocial(i,'platform',e.target.value)} className="input-field"><option value="">Choose platform</option>{SOCIAL_PLATFORMS.filter(p=>p===link.platform||!socialLinks.some((x,n)=>n!==i&&x.platform===p)).map(p=><option key={p} value={p}>{SOCIAL_LABELS[p]}</option>)}</select><input value={link.url} onChange={e=>setSocial(i,'url',e.target.value)} placeholder="https://…" className="input-field"/><button type="button" className="p-2 rounded-xl justify-self-end" onClick={()=>setSocialLinks(v=>v.filter((_,n)=>n!==i))} aria-label="Remove link"><X className="w-4 h-4"/></button></div>)}{socialLinks.length<3&&<button type="button" className="btn-ghost !w-auto" onClick={()=>setSocialLinks(v=>[...v,{platform: v.some(x=>x.platform==='instagram')?'goodreads':'instagram',url:''}])}><Plus className="w-4 h-4"/> Add another link</button>}</div></div></section>

    <section className="surface-card p-6"><div className="mb-5"><p className="text-xs uppercase tracking-[.18em] font-semibold" style={{color:'var(--color-teal-dark)'}}>Reading journey</p><h2 className="font-serif text-2xl font-semibold mt-1">Your reading life</h2><p className="text-sm mt-1" style={{color:'var(--color-text-muted)'}}>Your reading history, favourites and book-related profile details live here.</p></div><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><PrivacyField label="Reading Since" visible={visibility.reading_since} onToggle={()=>toggleVisibility('reading_since')}><input value={readingSince} onChange={e=>setReadingSince(e.target.value.replace(/\D/g,'').slice(0,4))} inputMode="numeric" placeholder="2024" maxLength={4} className="input-field"/></PrivacyField><PrivacyField label="Books Read This Month" visible={visibility.books_read_this_month} onToggle={()=>toggleVisibility('books_read_this_month')}><NumberField value={booksReadThisMonth} onChange={setBooksReadThisMonth} placeholder="3"/></PrivacyField><PrivacyField label="Total Books Read" visible={visibility.total_books_read} onToggle={()=>toggleVisibility('total_books_read')}><NumberField value={totalBooksRead} onChange={setTotalBooksRead} placeholder="102" min={accepted.length}/></PrivacyField><PrivacyField label="Favourite Book" visible={visibility.favorite_book} onToggle={()=>toggleVisibility('favorite_book')}><input value={favoriteBook} onChange={e=>setFavoriteBook(e.target.value)} placeholder="e.g. The Midnight Library" className="input-field"/></PrivacyField><PrivacyField label="Favourite Author" visible={visibility.favorite_author} onToggle={()=>toggleVisibility('favorite_author')}><input value={favoriteAuthor} onChange={e=>setFavoriteAuthor(e.target.value)} placeholder="e.g. Madeline Miller" className="input-field"/></PrivacyField><PrivacyField label="Favourite Genre" visible={visibility.favorite_genre} onToggle={()=>toggleVisibility('favorite_genre')}><input value={favoriteGenre} onChange={e=>setFavoriteGenre(e.target.value)} placeholder="e.g. Literary Fiction" className="input-field"/></PrivacyField><div className="rounded-2xl p-4" style={{background:'var(--color-paper)',border:'1px solid var(--color-border)'}}><p className="text-xs font-semibold">Published with Novelty Library</p><p className="text-2xl font-serif font-semibold mt-1" style={{color:'var(--color-cyan-dark)'}}>{published.length}</p><p className="text-xs mt-1" style={{color:'var(--color-text-muted)'}}>Only published reviews count — accepted/pending reviews are excluded.</p></div></div></section>

        {questions.filter(q=>q.section==='Book Journey').length>0&&<section className="surface-card p-6"><div className="mb-5"><p className="text-xs uppercase tracking-[.18em] font-semibold" style={{color:'var(--color-teal-dark)'}}>Reading journey · questions</p><h2 className="font-serif text-2xl font-semibold mt-1">The questions behind your reading life</h2><p className="text-sm mt-1" style={{color:'var(--color-text-muted)'}}>Book-related profile questions live here so your personal details stay focused.</p></div><div className="grid grid-cols-1 md:grid-cols-2 gap-4">{questions.filter(q=>q.section==='Book Journey').map(q=><QuestionField key={q.id} question={q} value={answers[q.key]} visible={visibility[`question:${q.key}`] ?? q.public_default} onVisibility={()=>toggleVisibility(`question:${q.key}`)} onChange={value=>setAnswers(v=>({...v,[q.key]:value}))}/>)}</div></section>}
    {questions.filter(q=>q.section!=='Book Journey').length>0&&<section className="surface-card p-6"><div className="mb-5"><p className="text-xs uppercase tracking-[.18em] font-semibold" style={{color:'var(--color-teal-dark)'}}>More about you</p><h2 className="font-serif text-2xl font-semibold mt-1">Profile questions</h2><p className="text-sm mt-1" style={{color:'var(--color-text-muted)'}}>These are created and ordered by Novelty Library admins. Each answer has its own eye control.</p></div><div className="space-y-6">{groupQuestions(questions.filter(q=>q.section!=='Book Journey')).map(([section,qs])=><div key={section}><h3 className="font-semibold text-sm mb-3" style={{color:'var(--color-cyan-dark)'}}>{section}</h3><div className="grid grid-cols-1 md:grid-cols-2 gap-4">{qs.map(q=><QuestionField key={q.id} question={q} value={answers[q.key]} visible={visibility[`question:${q.key}`] ?? q.public_default} onVisibility={()=>toggleVisibility(`question:${q.key}`)} onChange={value=>setAnswers(v=>({...v,[q.key]:value}))}/>)}</div></div>)}</div></section>}

    <section className="surface-card p-6"><div className="mb-5"><p className="text-xs uppercase tracking-[.18em] font-semibold" style={{color:'var(--color-teal-dark)'}}>Connections privacy</p><h2 className="font-serif text-2xl font-semibold mt-1">Follower lists</h2></div><div className="grid md:grid-cols-2 gap-3"><PrivacyTile label="Followers list" privateState={hideFollowers} onClick={()=>setHideFollowers(v=>!v)}/><PrivacyTile label="Following list" privateState={hideFollowing} onClick={()=>setHideFollowing(v=>!v)}/></div></section>

    {error&&<div className="p-4 rounded-2xl text-sm" style={{background:'rgba(239,68,68,.08)',color:'#ef4444'}}>{error}</div>}{saved&&<div className="p-4 rounded-2xl text-sm flex items-center gap-2" style={{background:'rgba(53,211,217,.1)',color:'var(--color-teal-dark)'}}><CheckCircle className="w-4 h-4"/> Profile saved.</div>}<button disabled={saving} className="btn-primary w-full disabled:opacity-50"><Save className="w-4 h-4"/>{saving?'Saving…':'Save Profile'}</button></form>

    <section className="surface-card p-6"><div className="flex items-center justify-between gap-4 mb-5"><div><p className="text-xs uppercase tracking-[.18em] font-semibold" style={{color:'var(--color-teal-dark)'}}>Published shelf</p><h2 className="font-serif text-2xl font-semibold">Published Reviews <span className="text-base font-sans font-semibold" style={{color:'var(--color-cyan-dark)'}}>({published.length})</span></h2></div><CheckCircle className="w-5 h-5" style={{color:'var(--color-cyan-dark)'}}/></div>{published.length?<div className="grid md:grid-cols-2 gap-4">{published.map(r=><AcceptedCard key={r.id} review={r} navigate={navigate} live/>)}</div>:<p className="py-8 text-center text-sm" style={{color:'var(--color-text-muted)'}}>Published reviews linked to your account will appear here.</p>}</section>
    <section className="surface-card p-6"><div className="flex items-center gap-2 mb-5"><Library className="w-5 h-5" style={{color:'var(--color-cyan-dark)'}}/><h2 className="font-serif text-2xl font-semibold">Accepted Reviews <span className="text-base font-sans font-semibold" style={{color:'var(--color-cyan-dark)'}}>({accepted.length})</span></h2></div>{accepted.length?<div className="grid md:grid-cols-2 gap-4">{accepted.map(r=><AcceptedCard key={r.id} review={r} navigate={navigate} publishedNos={publishedNos}/>)}</div>:<p className="py-8 text-center text-sm" style={{color:'var(--color-text-muted)'}}>No accepted reviews yet.</p>}</section>
    </div></div>;
}

function groupQuestions(qs:ProfileQuestion[]){const m=new Map<string,ProfileQuestion[]>();qs.forEach(q=>m.set(q.section,[...(m.get(q.section)||[]),q]));return [...m.entries()];}
function PrivacyField({label,visible,onToggle,children}:{label:string;visible:boolean;onToggle:()=>void;children:ReactNode}){return <div><div className="flex items-center justify-between mb-1.5"><label className="label !mb-0">{label}</label><PrivacyEye visible={visible} onToggle={onToggle}/></div>{children}</div>}
function PrivacyEye({visible,onToggle}:{visible:boolean;onToggle:()=>void}){return <button type="button" onClick={onToggle} className="relative group inline-flex items-center justify-center w-8 h-8 rounded-full" style={{background:visible?'rgba(8,145,178,.09)':'rgba(100,116,139,.09)',color:visible?'var(--color-teal-dark)':'var(--color-text-muted)'}} aria-label={visible?'Visible to everyone':'Private to you'}>{visible?<Eye className="w-4 h-4"/>:<EyeOff className="w-4 h-4"/>}<span className="absolute z-20 right-0 top-9 hidden group-hover:block whitespace-nowrap rounded-lg px-2.5 py-1.5 text-[10px] shadow-lg" style={{background:'#083344',color:'white'}}>{visible?'Visible to everyone':'Private to you'}</span></button>}
function QuestionField({question,value,visible,onVisibility,onChange}:{question:ProfileQuestion;value:unknown;visible:boolean;onVisibility:()=>void;onChange:(v:unknown)=>void}){return <PrivacyField label={question.question} visible={visible} onToggle={onVisibility}>{question.type==='long_text'?<textarea value={String(value??'')} onChange={e=>onChange(e.target.value)} className="input-field min-h-28"/>:question.type==='select'?<select value={String(value??'')} onChange={e=>onChange(e.target.value)} className="input-field"><option value="">Choose…</option>{question.options.map(o=><option key={o} value={o}>{o}</option>)}</select>:<input type={question.type==='number'?'number':question.type==='url'?'url':'text'} value={String(value??'')} onChange={e=>onChange(e.target.value)} className="input-field"/>}</PrivacyField>}
function PrivacyTile({label,privateState,onClick}:{label:string;privateState:boolean;onClick:()=>void}){return <button type="button" onClick={onClick} className="rounded-2xl p-4 text-left" style={{background:'var(--color-paper)',border:'1px solid var(--color-border)'}}><div className="flex items-center gap-2 font-semibold">{privateState?<Lock className="w-4 h-4"/>:<Unlock className="w-4 h-4"/>}{label}<span className="ml-auto text-xs font-normal">{privateState?'Private':'Visible'}</span></div></button>}
function NumberField({value,onChange,placeholder,min=0}:{value:string;onChange:(v:string)=>void;placeholder?:string;min?:number}){const safe=Math.max(min,Number(value)||0);return <div className="nl-number-field"><input value={value} onChange={e=>onChange(e.target.value.replace(/\D/g,''))} inputMode="numeric" placeholder={placeholder} className="input-field nl-number-input"/><div className="nl-number-stepper"><button type="button" onClick={()=>onChange(String(Math.max(min,safe-1)))} disabled={safe<=min}><Minus className="w-3.5 h-3.5"/></button><button type="button" onClick={()=>onChange(String(safe+1))}><Plus className="w-3.5 h-3.5"/></button></div></div>}
function AcceptedCard({review,navigate,live=false,publishedNos}:{review:AcceptedReviewCard;navigate?:(path:string)=>void;live?:boolean;publishedNos?:Set<string>}){const rating=Number(review.reviewers_rating);const isPublished=live||publishedNos?.has(String(review.review_no||''));const clickable=!!navigate&&!!isPublished;const path=`/review/${encodeURIComponent(`${review.book_title||'review'}-${review.review_no||''}`)}`;return <article className="rounded-2xl p-4 flex gap-4 transition-all hover:-translate-y-0.5" onClick={()=>clickable&&navigate?.(path)} style={{background:'var(--color-paper)',border:'1px solid var(--color-border)',cursor:clickable?'pointer':'default'}}><div className="w-20 h-28 rounded-xl overflow-hidden shrink-0">{review.book_cover?<img src={review.book_cover} alt="" className="w-full h-full object-cover"/>:<div className="w-full h-full grid place-items-center"><BookOpen className="w-7 h-7"/></div>}</div><div className="min-w-0"><div className="flex items-center gap-2"><p className="text-xs font-bold" style={{color:'var(--color-cyan-dark)'}}>Review #{review.review_no||'—'}</p>{isPublished&&<span className="text-[10px] uppercase tracking-wider font-bold px-2 py-1 rounded-full" style={{background:'rgba(0,151,178,.1)',color:'var(--color-teal-dark)'}}>Published · Open</span>}</div><h3 className="font-serif text-lg font-semibold mt-1">{review.book_title}</h3><p className="text-sm mt-1" style={{color:'var(--color-text-muted)'}}>{review.author}</p>{Number.isFinite(rating)&&rating>0&&<RwStarRating value={rating} size={15} className="mt-2"/>}<p className="text-xs mt-2 line-clamp-3" style={{color:'var(--color-text-muted)'}}>{review.review}</p>{isPublished&&<p className="text-[11px] mt-2 font-semibold" style={{color:'var(--color-cyan-dark)'}}>View published review →</p>}</div></article>}
