import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, BookOpen, CheckCircle, User, UserPlus, UserCheck, Users, X, Flag, AlertTriangle } from 'lucide-react';
import { useAuth } from '@/lib/auth';
import { fetchPublicProfile, fetchPublicPublishedReviews, type AcceptedReviewCard, type PublicProfileData } from '@/lib/reviews';
import { fetchFollowStats, followUsername, unfollowUsername, fetchConnections, fetchFollowPrivacy, type FollowStats, type ConnectionProfile, type FollowPrivacy } from '@/lib/social';
import { fetchProfileQuestions, isLegacyProfileFieldKey, type LegacyProfileFieldKey, type ProfileQuestion } from '@/lib/profileQuestions';
import { ProfileCard, asFormatKey, type ProfileCardData } from '@/components/ProfileCard';
import { answerText, answerImageUrls } from '@/components/ProfileQuestionAnswer';
import { RwStarRating } from '@/components/RwStarRating';
import { sanitizeUserText, safeExternalUrl } from '@/lib/sanitize';
import { isUserBlacklisted, reportUser, REPORT_REASONS, type ReportReason } from '@/lib/moderation';

interface Props { username: string; navigate: (path: string) => void; }
export function PublicProfilePage({ username, navigate }: Props) {
  const { user } = useAuth(); const [profile,setProfile]=useState<PublicProfileData|null>(null); const [published,setPublished]=useState<AcceptedReviewCard[]>([]); const [questions,setQuestions]=useState<ProfileQuestion[]>([]); const [follow,setFollow]=useState<FollowStats>({followers:0,following:0,is_following:false}); const [privacy,setPrivacy]=useState<FollowPrivacy>({hide_followers:false,hide_following:false}); const [connections,setConnections]=useState<ConnectionProfile[]>([]); const [connectionKind,setConnectionKind]=useState<'followers'|'following'|null>(null); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false);
  useEffect(()=>{
    let alive=true; setLoading(true);
    // allSettled: a failing optional piece (follow stats, privacy, questions) must never hide the profile or its published reviews.
    Promise.allSettled([fetchPublicProfile(username),fetchPublicPublishedReviews(username),fetchProfileQuestions(true),fetchFollowStats(username),fetchFollowPrivacy(username)]).then(([p,pub,q,stats,priv])=>{
      if(!alive) return;
      setProfile(p.status==='fulfilled'?p.value:null);
      setPublished(pub.status==='fulfilled'?pub.value:[]);
      setQuestions(q.status==='fulfilled'?q.value:[]);
      if(stats.status==='fulfilled') setFollow(stats.value);
      if(priv.status==='fulfilled') setPrivacy(priv.value);
    }).finally(()=>{ if(alive) setLoading(false); });
    return ()=>{ alive=false; };
  },[username]);
  const isOwn=!!user&&user.id===profile?.id;
  const [reportOpen,setReportOpen]=useState(false); const [reportReason,setReportReason]=useState<ReportReason>(REPORT_REASONS[0]); const [reportDetails,setReportDetails]=useState(''); const [reportBusy,setReportBusy]=useState(false); const [reportMessage,setReportMessage]=useState<string|null>(null); const [blacklisted,setBlacklisted]=useState(false);
  useEffect(()=>{ if(profile?.novelty_username) void isUserBlacklisted(profile.novelty_username).then(setBlacklisted).catch(()=>undefined); },[profile?.novelty_username]);
  const cardData:ProfileCardData|undefined=useMemo(()=>{
    if(!profile)return undefined;
    const avg=published.filter(r=>Number(r.reviewers_rating)>0);
    const answers=Object.fromEntries(questions.map(q=>{ const raw=(profile.profile_answers||{})[q.key]; if(q.type==='image_upload') return [sanitizeUserText(q.key,120), answerImageUrls(raw).map(url=>safeExternalUrl(url)).filter((url): url is string=>!!url)]; if(q.type==='select_multiple' && Array.isArray(raw)) return [sanitizeUserText(q.key,120), raw.map(v=>sanitizeUserText(answerText(v),180)).filter(Boolean)]; return [sanitizeUserText(q.key,120),sanitizeUserText(answerText(raw),1200)]; }));
    // Converted reading fields are real questions: they show only while their question is active and on the card.
    const readingConverted=questions.some(q=>isLegacyProfileFieldKey(q.key));
    const legacyOn=(k:LegacyProfileFieldKey)=>{ if(!readingConverted) return true; const q=questions.find(x=>x.key===k); return !!q&&q.active!==false&&q.show_in_profile_card!==false; };
    const safeQuestions=questions.filter(q=>!isLegacyProfileFieldKey(q.key)).map(q=>({...q,key:sanitizeUserText(q.key,120),question:sanitizeUserText(q.question,300)}));
    const socialLinks=(profile.social_links||[]).map(l=>({platform:sanitizeUserText(l.platform,40).toLowerCase(),url:safeExternalUrl(l.url)||''})).filter(l=>l.url);
    return {
      name:sanitizeUserText(profile.name,120)||null,
      username:sanitizeUserText(profile.novelty_username,80)||null,
      avatarUrl:safeExternalUrl(profile.avatar_url),
      headerImageUrl:safeExternalUrl(profile.header_image_url),
      socialLinks,
      instagram:(profile.profile_visibility?.instagram===false?null:sanitizeUserText(profile.instagram_id,80)||null),
      booksThisMonth:legacyOn('books_read_this_month')?profile.books_read_this_month:null,totalBooksRead:legacyOn('total_books_read')?profile.total_books_read:null,publishedBooks:published.length,
      avgRating:avg.length?avg.reduce((s,r)=>s+Number(r.reviewers_rating),0)/avg.length:null,
      readingSince:legacyOn('reading_since')?profile.reading_since:null,
      favoriteBook:legacyOn('favorite_book')?sanitizeUserText(profile.favorite_book,200)||null:null,
      favoriteAuthor:legacyOn('favorite_author')?sanitizeUserText(profile.favorite_author,160)||null:null,
      favoriteGenre:legacyOn('favorite_genre')?sanitizeUserText(profile.favorite_genre,120)||null:null,
      answers,questions:safeQuestions.filter(q => q.active !== false),
      publishedReviews:published.slice(0,6).map(r=>({id:r.id,reviewNo:sanitizeUserText(r.review_no,40)||null,title:sanitizeUserText(r.book_title,200)||'Untitled review',author:sanitizeUserText(r.author,160),coverUrl:safeExternalUrl(r.book_cover),rating:Number(r.reviewers_rating)||null}))
    };
  },[profile,published,questions]);
  const doFollow=async()=>{if(!user||busy)return;setBusy(true);try{if(follow.is_following)await unfollowUsername(username);else await followUsername(username);setFollow(await fetchFollowStats(username));}finally{setBusy(false);}};
  if(loading)return <div className="pt-32 pb-20 container-prose text-center">Loading profile…</div>;
  if(!profile||!cardData)return <div className="pt-32 pb-20 container-prose text-center max-w-md mx-auto"><User className="w-12 h-12 mx-auto mb-4"/><h1 className="font-serif text-2xl font-semibold mb-2">Profile not found</h1><p className="text-sm mb-6" style={{color:'var(--color-text-muted)'}}>That Novelty Library username is not attached to a public account.</p><button onClick={()=>navigate('/reviews')} className="btn-ghost"><ArrowLeft className="w-4 h-4"/> Back to Reviews</button></div>;
  return <div className="pt-24 pb-20 container-prose animate-fade-in"><button onClick={()=>navigate('/reviews')} className="inline-flex items-center gap-1.5 text-sm mb-7" style={{color:'var(--color-text-muted)'}}><ArrowLeft className="w-4 h-4"/> Reviews</button><div className="max-w-6xl mx-auto space-y-7">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[.18em] font-semibold" style={{color:'var(--color-teal-dark)'}}>Novelty Library profile</p><h1 className="font-serif text-4xl font-semibold mt-1">@{sanitizeUserText(profile.novelty_username||username.replace(/^@/,''), 60)}</h1>{blacklisted&&<span className="inline-flex items-center gap-1.5 mt-2 text-xs font-bold rounded-full px-2.5 py-1" style={{background:'rgba(239,68,68,.10)',color:'#b91c1c'}}><AlertTriangle className="w-3.5 h-3.5"/> Profile blacklisted</span>}</div><div className="flex flex-wrap gap-2">{!isOwn&&user&&<><button type="button" disabled={busy} onClick={doFollow} className="btn-primary !w-auto">{follow.is_following?<><UserCheck className="w-4 h-4"/> Following</>:<><UserPlus className="w-4 h-4"/> Follow</>}</button><button type="button" onClick={()=>{setReportMessage(null);setReportOpen(true)}} className="btn-ghost !w-auto"><Flag className="w-4 h-4"/> Report user</button></>}</div></div>
    <section className="grid grid-cols-1 lg:grid-cols-[minmax(0,1fr)_250px] gap-6 items-start"><ProfileCard data={cardData} download={isOwn} initialFormat={asFormatKey((profile.profile_answers||{}).__public_view)||undefined}/><aside className="surface-card p-5"><p className="text-xs uppercase tracking-wider font-semibold" style={{color:'var(--color-teal-dark)'}}>Community</p><div className="grid grid-cols-2 gap-3 mt-4"><Stat value={follow.followers} label="followers"/><Stat value={follow.following} label="following"/></div><div className="mt-4 text-xs" style={{color:'var(--color-text-muted)'}}>Published books/reviews with Novelty Library: <b style={{color:'var(--color-text)'}}>{published.length}</b></div></aside></section>
    <section className="surface-card p-6"><div className="flex flex-wrap items-center gap-4"><button type="button" className="nl-follow-count" onClick={async()=>{if(!isOwn&&privacy.hide_followers)return;setConnectionKind('followers');setConnections(await fetchConnections(username,'followers'));}}><strong>{follow.followers}</strong> followers</button><button type="button" className="nl-follow-count" onClick={async()=>{if(!isOwn&&privacy.hide_following)return;setConnectionKind('following');setConnections(await fetchConnections(username,'following'));}}><strong>{follow.following}</strong> following</button><span className="text-xs" style={{color:'var(--color-text-muted)'}}>User since {new Date(profile.created_at).toLocaleDateString()}</span></div></section>
    <Shelf title="Published reviews" subtitle="Reviews currently live in Novelty Library" reviews={published} navigate={navigate}/>
    {reportOpen&&<div className="fixed inset-0 z-[100] grid place-items-center p-4 bg-black/45 backdrop-blur-sm" role="dialog" aria-modal="true" onClick={()=>!reportBusy&&setReportOpen(false)}><div className="w-full max-w-lg rounded-3xl p-6" style={{background:'var(--color-paper)',border:'1px solid var(--color-border)'}} onClick={e=>e.stopPropagation()}><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><Flag className="w-5 h-5" style={{color:'var(--color-teal-dark)'}}/><h2 className="font-serif text-2xl font-semibold">Report this user</h2></div><p className="text-sm mt-1" style={{color:'var(--color-text-muted)'}}>Choose the closest reason. Reports are reviewed for moderation and repeated reports may trigger automatic blacklisting.</p></div><button type="button" onClick={()=>setReportOpen(false)} disabled={reportBusy}><X className="w-5 h-5"/></button></div><div className="mt-5 space-y-4"><div><label className="label">What should be reported?</label><select value={reportReason} onChange={e=>setReportReason(e.target.value as ReportReason)} className="input-field">{REPORT_REASONS.map(r=><option key={r}>{r}</option>)}</select></div><div><label className="label">Additional details (optional)</label><textarea value={reportDetails} onChange={e=>setReportDetails(e.target.value)} maxLength={2000} className="input-field min-h-28 resize-y" placeholder="Give moderators useful context without sharing unnecessary private information."/></div>{reportMessage&&<p className="text-sm" style={{color:/submitted|blacklisted/i.test(reportMessage)?'var(--color-teal-dark)':'#dc2626'}}>{reportMessage}</p>}<div className="flex gap-2"><button type="button" onClick={()=>setReportOpen(false)} disabled={reportBusy} className="btn-ghost flex-1">Cancel</button><button type="button" disabled={reportBusy} onClick={async()=>{setReportBusy(true);setReportMessage(null);try{const r=await reportUser(profile.id,reportReason,reportDetails);setReportMessage(r.blacklisted?'Report submitted. This profile has reached the automatic blacklist threshold.':'Report submitted. Thank you.');setReportDetails('');}catch(e){setReportMessage(e instanceof Error?e.message:'Could not submit report.')}finally{setReportBusy(false)}}} className="btn-primary flex-1">{reportBusy?'Submitting…':'Submit report'}</button></div></div></div></div>}
    {connectionKind&&<div className="fixed inset-0 z-[90] grid place-items-center p-4 bg-black/40 backdrop-blur-sm" onClick={()=>setConnectionKind(null)}><div className="w-full max-w-md max-h-[75vh] overflow-hidden rounded-3xl p-5" style={{background:'var(--color-paper)',border:'1px solid var(--color-border)'}} onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between mb-4"><h2 className="font-serif text-2xl font-semibold">{connectionKind==='followers'?'Followers':'Following'}</h2><button onClick={()=>setConnectionKind(null)}><X className="w-5 h-5"/></button></div><div className="overflow-y-auto space-y-2 max-h-[58vh]">{connections.map(person=><button key={person.id} type="button" className="w-full flex items-center gap-3 p-3 rounded-2xl text-left" onClick={()=>{setConnectionKind(null);if(person.novelty_username)navigate(`/profile/@${encodeURIComponent(person.novelty_username)}`)}}><span className="w-10 h-10 rounded-full overflow-hidden gradient-teal grid place-items-center text-white font-bold">{safeExternalUrl(person.avatar_url)?<img src={safeExternalUrl(person.avatar_url) || undefined} alt="" className="w-full h-full object-cover"/>:sanitizeUserText(person.name||'R',80).slice(0,1).toUpperCase()}</span><span><strong className="block">{sanitizeUserText(person.name||'Novelty Reader', 80)}</strong><span className="text-xs" style={{color:'var(--color-cyan-dark)'}}>@{sanitizeUserText(person.novelty_username||'reader', 60)}</span></span></button>)}</div></div></div>}
  </div></div>;
}
function Stat({value,label}:{value:number;label:string}){return <div className="rounded-xl p-3" style={{background:'var(--color-paper)',border:'1px solid var(--color-border)'}}><p className="text-xl font-semibold">{value}</p><p className="text-[10px] uppercase tracking-wider" style={{color:'var(--color-text-muted)'}}>{label}</p></div>}
function Shelf({title,subtitle,reviews,navigate}:{title:string;subtitle:string;reviews:AcceptedReviewCard[];navigate:(path:string)=>void}){return <section className="surface-card p-6"><div className="flex items-center justify-between gap-4 mb-5"><div><p className="text-xs uppercase tracking-[.18em] font-semibold" style={{color:'var(--color-teal-dark)'}}>{subtitle}</p><h2 className="font-serif text-2xl font-semibold">{title}</h2></div><CheckCircle className="w-5 h-5" style={{color:'var(--color-cyan-dark)'}}/></div>{reviews.length?<div className="grid md:grid-cols-2 gap-4">{reviews.map(r=><ReviewCard key={r.id} review={r} navigate={navigate}/>)}</div>:<div className="py-8 text-center text-sm" style={{color:'var(--color-text-muted)'}}><BookOpen className="w-8 h-8 mx-auto mb-3"/>No published reviews yet.</div>}</section>}
function ReviewCard({review,navigate}:{review:AcceptedReviewCard;navigate:(path:string)=>void}){const rating=Number(review.reviewers_rating);return <article className="rounded-2xl p-4 flex gap-4 cursor-pointer" onClick={()=>navigate(`/review/${encodeURIComponent(`${review.book_title||'review'}-${review.review_no||''}`)}`)} style={{background:'var(--color-paper)',border:'1px solid var(--color-border)'}}><div className="w-20 h-28 rounded-xl overflow-hidden shrink-0">{review.book_cover?<img src={review.book_cover} alt="" className="w-full h-full object-cover"/>:<div className="w-full h-full grid place-items-center"><BookOpen className="w-7 h-7"/></div>}</div><div className="min-w-0"><p className="text-xs font-bold" style={{color:'var(--color-cyan-dark)'}}>Review #{review.review_no||'—'}</p><h3 className="font-serif text-lg font-semibold mt-1">{sanitizeUserText(review.book_title, 200)}</h3><p className="text-sm mt-1" style={{color:'var(--color-text-muted)'}}>{sanitizeUserText(review.author, 120)}</p>{rating>0&&<RwStarRating value={rating} size={15} className="mt-2"/>}<p className="text-xs mt-2 line-clamp-3" style={{color:'var(--color-text-muted)'}}>{sanitizeUserText(review.review, 800)}</p></div></article>}
